-- SQLITE
INSERT INTO questions (question, answer1, answer2, answer3, answer4, correct_answer)
VALUES 
('What is the capital of Uruguay?', 'Montenegro', 'Montepelo', 'Montecarlo', 'Montevideo', 4),
('Which planet is known as the Red Planet?', 'Earth', 'Mars', 'Jupiter', 'Venus', 2),
('Who wrote "Hamlet"?', 'Dickens', 'Shakespeare', 'Chaucer', 'Austen', 2),
('What is the boiling point of water?', '90°C', '100°C', '110°C', '120°C', 2),
('What is the largest mammal?', 'Elephant', 'Gorilla', 'Blue Whale', 'Orca', 2),
('Which name does ''War Machine'' also go by?', 'Metal Warhorse', 'Steel Warrior', 'Iron Patriot', 'Captain Legend', 3),
('What is the flavour associated with the ''Oreo'' cookie?', 'Cookies and Cream', 'Rocky Road', 'Vanilla and Mousse', 'Mint', 1),
('In the story of Snow White, how many dwarfs are there?', '4', '5', '7', '6', 3),
('What is the main ingredient in the dish ''sushi''?', 'Fish', 'Seaweed', 'Wasabi', 'Rice', 4),
('How many sides does a hexagon have?','4', '5', '6', '7',3),
('Which video game features a character named "Link"?', 'Mario', 'Zelda', 'Metroid', 'Pokemon', 2),
('Which game series features the character "Master Chief"?', 'Halo', 'Call of Duty', 'Battlefield', 'Overwatch', 1),
('In "Minecraft", what material do you not need to create a pickaxe?', 'Iron', 'Emerald', 'Diamond', 'Gold', 2),
('What is the name of the robot playable character in ''Apex Legends?''', 'Pathfinder', 'Astro', 'Bastion', 'M.O.D.O.K', 1),
('Who is the enemy of ''Mr. Mxyzptlk''?', 'Batman', 'Spiderman', 'Ironman', 'Superman', 4),
('Who was the leader of the Soviet Union during the Cuban Missile Crisis?', 'Joseph Stalin', 'Nikita Khrushchev', 'Leonid Brezhnev', 'Mikhail Gorbachev', 2),
('What is the ''powerhouse of the cell?''', 'Nucleus', 'Ribosome', 'Mitochondrion', 'Endoplasmic Reticulum', 3),
('Which country was led by Fidel Castro from 1959 until his retirement?', 'Venezuela', 'Cuba', 'Brazil', 'Argentina', 2),
('What is the name of the world''s largest desert?', 'Sahara', 'Kalahari', 'Gobi', 'Antarctica', 4),
('What is the name of the first artificial Earth satellite launched by the Soviet Union in 1957?', 'Sputnik 1', 'Vostok 1', 'Luna 1', 'Kosmos 1', 1),
('What is the only country that is also a continent?', 'United States', 'Australia', 'South Africa', 'Ireland', 2),
('Which animal has the largest brain in relation to body size?', 'Sperm Whale', 'Dolphin', 'Elephant', 'Ant', 4),
('Which one of these names belongs to a character in Dragon Ball Z?', 'Uub', 'Uud', 'Uul', 'Uuk', 1),
('What is the official animal of Scotland?', 'Dragon', 'Werewolf', 'Unicorn', 'Dinosaur', 3),
('What animal is known for its long neck and spots on its body?', 'Giraffe', 'Zebra', 'Cheetah', 'Leopard', 1),
('What is the shortcut for the “copy” function on most computers?', 'CTRL C', 'CTRL D', 'CTRL V', 'SHIFT C', 3),
('Night Crawler, member of the X-Men, has what kind of powers?', 'Teleportation', 'Invisibility', 'Laser Beams', 'Time Control', 1),
('Who wrote ''The Odyssey?''', 'Bart', 'Lisa', 'Homer', 'Ned', 3),
('In what year did the Chernobyl disaster occur?', '1951', '1976', '1991', '1986', 4),
('Who owns the stand ''Scary Monsters''?', 'David Bowie', 'Darius Brand', 'Diego Brando', 'Draymond Blackshear', 3);
